# generated by datamodel-codegen:
#   filename:  tags.yaml
#   timestamp: 2024-08-30T12:31:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel

from . import JSON_API_1


class FilterTagType(Enum):
    SYNC = "sync"
    ASYNC_ = "async"


class FilterTemplate(Enum):
    ADROLL = "adroll"
    BING_ADS = "bing_ads"
    CRAZY_EGG = "crazy_egg"
    CUSTOM_CONTENT = "custom_content"
    CUSTOM_POPUP = "custom_popup"
    CUSTOM_TAG = "custom_tag"
    DOUBLECLICK_FLOODLIGHT = "doubleclick_floodlight"
    FACEBOOK_RETARGETING_PIXEL = "facebook_retargeting_pixel"
    GOOGLE_ANALYTICS = "google_analytics"
    HOT_JAR = "hot_jar"
    HUB_SPOT = "hub_spot"
    LINKEDIN = "linkedin"
    MARKETO = "marketo"
    MAUTIC = "mautic"
    PIWIK = "piwik"
    PIWIK_CUSTOM_DIMENSION = "piwik_custom_dimension"
    PIWIK_EVENT = "piwik_event"
    PIWIK_GOAL_CONVERSION = "piwik_goal_conversion"
    PIWIK_VIRTUAL_PAGE_VIEW = "piwik_virtual_page_view"
    QUALAROO = "qualaroo"
    SALES_MANAGO = "sales_manago"
    SALESFORCE_PARDOT = "salesforce_pardot"
    VIDEO_HTML5 = "video_html5"
    VIDEO_YOUTUBE = "video_youtube"
    HEATMAPS = "heatmaps"
    ABANDONED = "abandoned"
    ECOMMERCE_ORDER = "ecommerce_order"
    ECOMMERCE_ADD_TO_CART = "ecommerce_add_to_cart"
    ECOMMERCE_REMOVE_FROM_CART = "ecommerce_remove_from_cart"
    ECOMMERCE_PRODUCT_DETAIL_VIEW = "ecommerce_product_detail_view"
    ECOMMERCE_CART_UPDATE = "ecommerce_cart_update"
    COOKIE_INFORMATION_CMP_INTEGRATION = "cookie_information_cmp_integration"
    AB_TASTY = "ab_tasty"
    CLICK_TALE = "click_tale"
    GOOGLE_ADWORDS = "google_adwords"
    OPTIMIZELY = "optimizely"
    VISUAL_WEBSITE_OPTIMIZER = "visual_website_optimizer"


class SortEnum(Enum):
    NAME = "name"
    FIELD_NAME = "-name"
    IS_ACTIVE = "is_active"
    FIELD_IS_ACTIVE = "-is_active"
    TAG_TYPE = "tag_type"
    FIELD_TAG_TYPE = "-tag_type"
    PRIORITY = "priority"
    FIELD_PRIORITY = "-priority"
    CREATED_AT = "created_at"
    FIELD_CREATED_AT = "-created_at"
    UPDATED_AT = "updated_at"
    FIELD_UPDATED_AT = "-updated_at"


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int = Field(..., description="Total number of elements", ge=0)


class Null(Enum):
    NONE_TYPE_NONE = None


class Links(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    test: int
    test_2: int = 1

    self: AnyUrl = Field(..., description="Link to current page")
    self2: AnyUrl = Field(None, description="Link to current page")
    first: Optional[Union[AnyUrl, Null]] = Field(default=None, description="Link to first page")
    last: Optional[Union[AnyUrl, Null]] = Field(default=None, description="Link to last page")
    prev: Optional[Union[AnyUrl, Null]] = Field(default=None, description="Link to previous page")
    next: Optional[Union[AnyUrl, Null]] = Field(default=None, description="Link to next page")


class ApiTagV1AppIdTagsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: List[JSON_API_1.Field0ListResponseDatum] = Field(..., title="JSON:API 1.0 list response data")
    meta: Meta = Field(..., description="Meta information about resources")
    links: Links = Field(..., description="Pagination links")


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pointer: Optional[str] = Field(
        default=None,
        description="A JSON Pointer [RFC6901] to the associated entity in the request document.",
    )
    parameter: Optional[str] = Field(
        default=None,
        description="A string indicating which URI parameter caused the error.",
    )


class Meta1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    keyword: Optional[str] = None
    keyword_args: Optional[Dict[str, Any]] = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="An application-specific error code, expressed as a string value.",
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem.",
    )
    source: Optional[Source] = Field(
        default=None,
        description="An object containing references to the source of the error.",
    )
    meta: Optional[Meta1] = Field(
        default=None,
        description="An object containing additional application-specific information about error.",
    )


class ApiTagV1AppIdTagsGetResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error] = Field(..., min_length=1)


class Error1(Error):
    pass


class ApiTagV1AppIdTagsGetResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error1] = Field(..., min_length=1)


class Error2(Error):
    pass


class ApiTagV1AppIdTagsGetResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error2] = Field(..., min_length=1)


class Error3(Error):
    pass


class ApiTagV1AppIdTagsGetResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error3] = Field(..., min_length=1)


class ApiTagV1AppIdTagsPatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: List[JSON_API_1.Field0RequestDatum] = Field(..., title="JSON:API 1.0 request data")


class Error4(Error):
    pass


class ApiTagV1AppIdTagsPatchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error4] = Field(..., min_length=1)


class Error5(Error):
    pass


class ApiTagV1AppIdTagsPatchResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error5] = Field(..., min_length=1)


class Error6(Error):
    pass


class ApiTagV1AppIdTagsPatchResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error6] = Field(..., min_length=1)


class Error7(Error):
    pass


class ApiTagV1AppIdTagsPatchResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error7] = Field(..., min_length=1)


class Error8(Error):
    pass


class ApiTagV1AppIdTagsPatchResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error8] = Field(..., min_length=1)


class DateDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: str = Field(
        ...,
        alias="from",
        description="format: Y-m-d\\TH:i:sO (https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601)",
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+[0-9]{4}$",
        title="Date",
    )
    to: str = Field(
        ...,
        description="format: Y-m-d\\TH:i:sO (https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601)",
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+[0-9]{4}$",
        title="Date",
    )
    timezone: str = Field(
        ...,
        description="Time zone definition (https://www.php.net/manual/en/timezones.php#timezones)",
        title="Timezone",
    )


class TimeDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: str = Field(
        ...,
        alias="from",
        description="format: H:i:s (https://www.php.net/manual/en/function.date.php#refsect1-function.date-parameters)",
        pattern="^[0-9]{2}:[0-9]{2}:[0-9]{2}$",
        title="Time",
    )
    to: str = Field(
        ...,
        description="format: H:i:s (https://www.php.net/manual/en/function.date.php#refsect1-function.date-parameters)",
        pattern="^[0-9]{2}:[0-9]{2}:[0-9]{2}$",
        title="Time",
    )
    timezone: str = Field(
        ...,
        description="Time zone definition (https://www.php.net/manual/en/timezones.php#timezones)",
        title="Timezone",
    )


class Type(Enum):
    TRIGGER = "trigger"


class TriggerRelationshipItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Trigger identifier",
        pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        title="UUID",
    )
    type: Type = Field(..., description="Trigger resource type")


class CustomTagAsynchronous(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestData = Field(..., title="JSON:API 1.0 request data")


class VariableReference(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ...,
        description="Tag Manager's variable reference, example `{{ Campaign }}`",
        pattern="^{{((?:.(?!}}))*.)}}$",
        title="Variable reference",
    )


class TriggerRelationshipItem1(TriggerRelationshipItem):
    pass


class CustomContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem2(TriggerRelationshipItem):
    pass


class CustomPopup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel1 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem3(TriggerRelationshipItem):
    pass


class PiwikPROTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel2 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem4(TriggerRelationshipItem):
    pass


class PiwikPROCustomDimensionsTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel3 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem5(TriggerRelationshipItem):
    pass


class PiwikPROCustomEventTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel4 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem6(TriggerRelationshipItem):
    pass


class PiwikPROGoalConversionTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel5 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem7(TriggerRelationshipItem):
    pass


class PiwikPROVirtualPageViewTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel6 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem8(TriggerRelationshipItem):
    pass


class AdrollTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel7 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem9(TriggerRelationshipItem):
    pass


class BingAdsTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel8 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem10(TriggerRelationshipItem):
    pass


class CrazyEggTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel9 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem11(TriggerRelationshipItem):
    pass


class FloodlightSalesItemSoldTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel10 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem12(TriggerRelationshipItem):
    pass


class FloodlightSalesTransactionsTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel11 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem13(TriggerRelationshipItem):
    pass


class FloodlightCounterSessionTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel12 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem14(TriggerRelationshipItem):
    pass


class FloodlightCounterStandardMethodTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel13 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem15(TriggerRelationshipItem):
    pass


class FloodlightCounterUniqueMethodTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel14 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem16(TriggerRelationshipItem):
    pass


class MetaPixelTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel15 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem17(TriggerRelationshipItem):
    pass


class GoogleAdsRemarketingTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel16 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem18(TriggerRelationshipItem):
    pass


class GoogleAdsTrackingConversionTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel17 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem19(TriggerRelationshipItem):
    pass


class GoogleAnalyticsTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel18 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem20(TriggerRelationshipItem):
    pass


class HotjarTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel19 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem21(TriggerRelationshipItem):
    pass


class HubSpotTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel20 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem22(TriggerRelationshipItem):
    pass


class LinkedInTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel21 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem23(TriggerRelationshipItem):
    pass


class MarketoTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel22 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem24(TriggerRelationshipItem):
    pass


class MauticTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel23 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem25(TriggerRelationshipItem):
    pass


class QualarooTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel24 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem26(TriggerRelationshipItem):
    pass


class SALESmanagoTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel25 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem27(TriggerRelationshipItem):
    pass


class SalesforcePardotTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel26 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem28(TriggerRelationshipItem):
    pass


class VideoHTML5Tag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel27 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem29(TriggerRelationshipItem):
    pass


class VideoYouTubeTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel28 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem30(TriggerRelationshipItem):
    pass


class HeatmapsTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel29 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem31(TriggerRelationshipItem):
    pass


class AbandonedTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel30 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem32(TriggerRelationshipItem):
    pass


class EcommerceOrder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel31 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem33(TriggerRelationshipItem):
    pass


class EcommerceAddToCart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel32 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem34(TriggerRelationshipItem):
    pass


class EcommerceRemoveFromCart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel33 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem35(TriggerRelationshipItem):
    pass


class EcommerceProductDetailView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel34 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem36(TriggerRelationshipItem):
    pass


class EcommerceCartUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel35 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem37(TriggerRelationshipItem):
    pass


class CookieInformationCMPIntegrationTag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel36 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem38(TriggerRelationshipItem):
    pass


class CustomTagSynchronousDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel37 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem39(TriggerRelationshipItem):
    pass


class ABTastyTagDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel38 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem40(TriggerRelationshipItem):
    pass


class ClicktaleTagDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel39 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem41(TriggerRelationshipItem):
    pass


class DoubleClickConversionTagDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel40 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem42(TriggerRelationshipItem):
    pass


class OptimizelyTagDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel41 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem43(TriggerRelationshipItem):
    pass


class VisualWebsiteOptimizerTagDEPRECATED(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel42 = Field(..., title="JSON:API 1.0 request data")


class ApiTagV1AppIdTagsPostRequest(
    RootModel[
        Union[
            CustomTagAsynchronous,
            CustomContent,
            CustomPopup,
            PiwikPROTag,
            PiwikPROCustomDimensionsTag,
            PiwikPROCustomEventTag,
            PiwikPROGoalConversionTag,
            PiwikPROVirtualPageViewTag,
            AdrollTag,
            BingAdsTag,
            CrazyEggTag,
            FloodlightSalesItemSoldTag,
            FloodlightSalesTransactionsTag,
            FloodlightCounterSessionTag,
            FloodlightCounterStandardMethodTag,
            FloodlightCounterUniqueMethodTag,
            MetaPixelTag,
            GoogleAdsRemarketingTag,
            GoogleAdsTrackingConversionTag,
            GoogleAnalyticsTag,
            HotjarTag,
            HubSpotTag,
            LinkedInTag,
            MarketoTag,
            MauticTag,
            QualarooTag,
            SALESmanagoTag,
            SalesforcePardotTag,
            VideoHTML5Tag,
            VideoYouTubeTag,
            HeatmapsTag,
            AbandonedTag,
            EcommerceOrder,
            EcommerceAddToCart,
            EcommerceRemoveFromCart,
            EcommerceProductDetailView,
            EcommerceCartUpdate,
            CookieInformationCMPIntegrationTag,
            CustomTagSynchronousDEPRECATED,
            ABTastyTagDEPRECATED,
            ClicktaleTagDEPRECATED,
            DoubleClickConversionTagDEPRECATED,
            OptimizelyTagDEPRECATED,
            VisualWebsiteOptimizerTagDEPRECATED,
        ]
    ]
):
    root: Union[
        CustomTagAsynchronous,
        CustomContent,
        CustomPopup,
        PiwikPROTag,
        PiwikPROCustomDimensionsTag,
        PiwikPROCustomEventTag,
        PiwikPROGoalConversionTag,
        PiwikPROVirtualPageViewTag,
        AdrollTag,
        BingAdsTag,
        CrazyEggTag,
        FloodlightSalesItemSoldTag,
        FloodlightSalesTransactionsTag,
        FloodlightCounterSessionTag,
        FloodlightCounterStandardMethodTag,
        FloodlightCounterUniqueMethodTag,
        MetaPixelTag,
        GoogleAdsRemarketingTag,
        GoogleAdsTrackingConversionTag,
        GoogleAnalyticsTag,
        HotjarTag,
        HubSpotTag,
        LinkedInTag,
        MarketoTag,
        MauticTag,
        QualarooTag,
        SALESmanagoTag,
        SalesforcePardotTag,
        VideoHTML5Tag,
        VideoYouTubeTag,
        HeatmapsTag,
        AbandonedTag,
        EcommerceOrder,
        EcommerceAddToCart,
        EcommerceRemoveFromCart,
        EcommerceProductDetailView,
        EcommerceCartUpdate,
        CookieInformationCMPIntegrationTag,
        CustomTagSynchronousDEPRECATED,
        ABTastyTagDEPRECATED,
        ClicktaleTagDEPRECATED,
        DoubleClickConversionTagDEPRECATED,
        OptimizelyTagDEPRECATED,
        VisualWebsiteOptimizerTagDEPRECATED,
    ] = Field(..., description="Tag create request")


class TriggerRelationshipItem44(TriggerRelationshipItem):
    pass


class CustomTagAsynchronous1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseData = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem45(TriggerRelationshipItem):
    pass


class CustomContent1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem46(TriggerRelationshipItem):
    pass


class CustomPopup1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel1 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem47(TriggerRelationshipItem):
    pass


class PiwikPROTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel2 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem48(TriggerRelationshipItem):
    pass


class PiwikPROCustomDimensionsTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel3 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem49(TriggerRelationshipItem):
    pass


class PiwikPROCustomEventTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel4 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem50(TriggerRelationshipItem):
    pass


class PiwikPROGoalConversionTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel5 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem51(TriggerRelationshipItem):
    pass


class PiwikPROVirtualPageViewTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel6 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem52(TriggerRelationshipItem):
    pass


class AdrollTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel7 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem53(TriggerRelationshipItem):
    pass


class BingAdsTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel8 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem54(TriggerRelationshipItem):
    pass


class CrazyEggTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel9 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem55(TriggerRelationshipItem):
    pass


class FloodlightSalesItemSoldTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel10 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem56(TriggerRelationshipItem):
    pass


class FloodlightSalesTransactionsTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel11 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem57(TriggerRelationshipItem):
    pass


class FloodlightCounterSessionTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel12 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem58(TriggerRelationshipItem):
    pass


class FloodlightCounterStandardMethodTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel13 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem59(TriggerRelationshipItem):
    pass


class FloodlightCounterUniqueMethodTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel14 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem60(TriggerRelationshipItem):
    pass


class MetaPixelTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel15 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem61(TriggerRelationshipItem):
    pass


class GoogleAdsRemarketingTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel16 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem62(TriggerRelationshipItem):
    pass


class GoogleAdsTrackingConversionTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel17 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem63(TriggerRelationshipItem):
    pass


class GoogleAnalyticsTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel18 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem64(TriggerRelationshipItem):
    pass


class HotjarTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel19 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem65(TriggerRelationshipItem):
    pass


class HubSpotTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel20 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem66(TriggerRelationshipItem):
    pass


class LinkedInTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel21 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem67(TriggerRelationshipItem):
    pass


class MarketoTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel22 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem68(TriggerRelationshipItem):
    pass


class MauticTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel23 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem69(TriggerRelationshipItem):
    pass


class QualarooTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel24 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem70(TriggerRelationshipItem):
    pass


class SALESmanagoTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel25 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem71(TriggerRelationshipItem):
    pass


class SalesforcePardotTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel26 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem72(TriggerRelationshipItem):
    pass


class VideoHTML5Tag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel27 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem73(TriggerRelationshipItem):
    pass


class VideoYouTubeTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel28 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem74(TriggerRelationshipItem):
    pass


class HeatmapsTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel29 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem75(TriggerRelationshipItem):
    pass


class AbandonedTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel30 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem76(TriggerRelationshipItem):
    pass


class EcommerceOrder1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel31 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem77(TriggerRelationshipItem):
    pass


class EcommerceAddToCart1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel32 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem78(TriggerRelationshipItem):
    pass


class EcommerceRemoveFromCart1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel33 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem79(TriggerRelationshipItem):
    pass


class EcommerceProductDetailView1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel34 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem80(TriggerRelationshipItem):
    pass


class EcommerceCartUpdate1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel35 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem81(TriggerRelationshipItem):
    pass


class CookieInformationCMPIntegrationTag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel36 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem82(TriggerRelationshipItem):
    pass


class CustomTagSynchronousDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel37 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem83(TriggerRelationshipItem):
    pass


class ABTastyTagDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel38 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem84(TriggerRelationshipItem):
    pass


class ClicktaleTagDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel39 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem85(TriggerRelationshipItem):
    pass


class DoubleClickConversionTagDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel40 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem86(TriggerRelationshipItem):
    pass


class OptimizelyTagDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel41 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem87(TriggerRelationshipItem):
    pass


class VisualWebsiteOptimizerTagDEPRECATED1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel42 = Field(..., title="JSON:API 1.0 response data")


class ApiTagV1AppIdTagsPostResponse(
    RootModel[
        Union[
            CustomTagAsynchronous1,
            CustomContent1,
            CustomPopup1,
            PiwikPROTag1,
            PiwikPROCustomDimensionsTag1,
            PiwikPROCustomEventTag1,
            PiwikPROGoalConversionTag1,
            PiwikPROVirtualPageViewTag1,
            AdrollTag1,
            BingAdsTag1,
            CrazyEggTag1,
            FloodlightSalesItemSoldTag1,
            FloodlightSalesTransactionsTag1,
            FloodlightCounterSessionTag1,
            FloodlightCounterStandardMethodTag1,
            FloodlightCounterUniqueMethodTag1,
            MetaPixelTag1,
            GoogleAdsRemarketingTag1,
            GoogleAdsTrackingConversionTag1,
            GoogleAnalyticsTag1,
            HotjarTag1,
            HubSpotTag1,
            LinkedInTag1,
            MarketoTag1,
            MauticTag1,
            QualarooTag1,
            SALESmanagoTag1,
            SalesforcePardotTag1,
            VideoHTML5Tag1,
            VideoYouTubeTag1,
            HeatmapsTag1,
            AbandonedTag1,
            EcommerceOrder1,
            EcommerceAddToCart1,
            EcommerceRemoveFromCart1,
            EcommerceProductDetailView1,
            EcommerceCartUpdate1,
            CookieInformationCMPIntegrationTag1,
            CustomTagSynchronousDEPRECATED1,
            ABTastyTagDEPRECATED1,
            ClicktaleTagDEPRECATED1,
            DoubleClickConversionTagDEPRECATED1,
            OptimizelyTagDEPRECATED1,
            VisualWebsiteOptimizerTagDEPRECATED1,
        ]
    ]
):
    root: Union[
        CustomTagAsynchronous1,
        CustomContent1,
        CustomPopup1,
        PiwikPROTag1,
        PiwikPROCustomDimensionsTag1,
        PiwikPROCustomEventTag1,
        PiwikPROGoalConversionTag1,
        PiwikPROVirtualPageViewTag1,
        AdrollTag1,
        BingAdsTag1,
        CrazyEggTag1,
        FloodlightSalesItemSoldTag1,
        FloodlightSalesTransactionsTag1,
        FloodlightCounterSessionTag1,
        FloodlightCounterStandardMethodTag1,
        FloodlightCounterUniqueMethodTag1,
        MetaPixelTag1,
        GoogleAdsRemarketingTag1,
        GoogleAdsTrackingConversionTag1,
        GoogleAnalyticsTag1,
        HotjarTag1,
        HubSpotTag1,
        LinkedInTag1,
        MarketoTag1,
        MauticTag1,
        QualarooTag1,
        SALESmanagoTag1,
        SalesforcePardotTag1,
        VideoHTML5Tag1,
        VideoYouTubeTag1,
        HeatmapsTag1,
        AbandonedTag1,
        EcommerceOrder1,
        EcommerceAddToCart1,
        EcommerceRemoveFromCart1,
        EcommerceProductDetailView1,
        EcommerceCartUpdate1,
        CookieInformationCMPIntegrationTag1,
        CustomTagSynchronousDEPRECATED1,
        ABTastyTagDEPRECATED1,
        ClicktaleTagDEPRECATED1,
        DoubleClickConversionTagDEPRECATED1,
        OptimizelyTagDEPRECATED1,
        VisualWebsiteOptimizerTagDEPRECATED1,
    ] = Field(..., description="Tag create response")


class Error9(Error):
    pass


class ApiTagV1AppIdTagsPostResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error9] = Field(..., min_length=1)


class Error10(Error):
    pass


class ApiTagV1AppIdTagsPostResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error10] = Field(..., min_length=1)


class Error11(Error):
    pass


class ApiTagV1AppIdTagsPostResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error11] = Field(..., min_length=1)


class Error12(Error):
    pass


class ApiTagV1AppIdTagsPostResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error12] = Field(..., min_length=1)


class Error13(Error):
    pass


class ApiTagV1AppIdTagsPostResponse5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error13] = Field(..., min_length=1)


class FilterTriggerType(Enum):
    PAGE_VIEW = "page_view"
    PAGE_LOAD = "page_load"
    DOM_READY = "dom_ready"
    LEAVE_CONTENT = "leave_content"
    PAGE_SCROLL = "page_scroll"
    TIME_ON_WEBSITE = "time_on_website"
    EVENT = "event"
    HISTORY = "history"
    DEBOUNCED_HISTORY = "debounced_history"
    FORM_SUBMISSION = "form_submission"
    CLICK = "click"
    CAPTURING_CLICK = "capturing_click"
    ELEMENT_PRESENCE = "element_presence"
    CDP_AUDIENCE_DETECTION = "cdp_audience_detection"
    ABANDONED = "abandoned"


class SortEnum1(Enum):
    NAME = "name"
    FIELD_NAME = "-name"
    CREATED_AT = "created_at"
    FIELD_CREATED_AT = "-created_at"
    UPDATED_AT = "updated_at"
    FIELD_UPDATED_AT = "-updated_at"


class Meta15(Meta):
    pass


class Links1(Links):
    pass


class ApiTagV1AppIdTagsTagIdTriggersGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: List[JSON_API_1.Field0ListResponseDatumModel] = Field(..., title="JSON:API 1.0 list response data")
    meta: Meta15 = Field(..., description="Meta information about resources")
    links: Links1 = Field(..., description="Pagination links")


class Meta16(Meta1):
    pass


class Error14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="An application-specific error code, expressed as a string value.",
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem.",
    )
    source: Optional[Source] = Field(
        default=None,
        description="An object containing references to the source of the error.",
    )
    meta: Optional[Meta16] = Field(
        default=None,
        description="An object containing additional application-specific information about error.",
    )


class ApiTagV1AppIdTagsTagIdTriggersGetResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error14] = Field(..., min_length=1)


class Error15(Error14):
    pass


class ApiTagV1AppIdTagsTagIdTriggersGetResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error15] = Field(..., min_length=1)


class Error16(Error14):
    pass


class ApiTagV1AppIdTagsTagIdTriggersGetResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error16] = Field(..., min_length=1)


class Error17(Error14):
    pass


class ApiTagV1AppIdTagsTagIdTriggersGetResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error17] = Field(..., min_length=1)


class TriggerRelationshipItem88(TriggerRelationshipItem):
    pass


class CustomTagAsynchronous2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel43 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem89(TriggerRelationshipItem):
    pass


class CustomContent2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel44 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem90(TriggerRelationshipItem):
    pass


class CustomPopup2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel45 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem91(TriggerRelationshipItem):
    pass


class PiwikPROTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel46 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem92(TriggerRelationshipItem):
    pass


class PiwikPROCustomDimensionsTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel47 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem93(TriggerRelationshipItem):
    pass


class PiwikPROCustomEventTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel48 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem94(TriggerRelationshipItem):
    pass


class PiwikPROGoalConversionTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel49 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem95(TriggerRelationshipItem):
    pass


class PiwikPROVirtualPageViewTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel50 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem96(TriggerRelationshipItem):
    pass


class AdrollTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel51 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem97(TriggerRelationshipItem):
    pass


class BingAdsTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel52 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem98(TriggerRelationshipItem):
    pass


class CrazyEggTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel53 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem99(TriggerRelationshipItem):
    pass


class FloodlightSalesItemSoldTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel54 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem100(TriggerRelationshipItem):
    pass


class FloodlightSalesTransactionsTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel55 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem101(TriggerRelationshipItem):
    pass


class FloodlightCounterSessionTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel56 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem102(TriggerRelationshipItem):
    pass


class FloodlightCounterStandardMethodTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel57 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem103(TriggerRelationshipItem):
    pass


class FloodlightCounterUniqueMethodTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel58 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem104(TriggerRelationshipItem):
    pass


class MetaPixelTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel59 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem105(TriggerRelationshipItem):
    pass


class GoogleAdsRemarketingTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel60 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem106(TriggerRelationshipItem):
    pass


class GoogleAdsTrackingConversionTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel61 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem107(TriggerRelationshipItem):
    pass


class GoogleAnalyticsTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel62 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem108(TriggerRelationshipItem):
    pass


class HotjarTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel63 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem109(TriggerRelationshipItem):
    pass


class HubSpotTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel64 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem110(TriggerRelationshipItem):
    pass


class LinkedInTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel65 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem111(TriggerRelationshipItem):
    pass


class MarketoTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel66 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem112(TriggerRelationshipItem):
    pass


class MauticTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel67 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem113(TriggerRelationshipItem):
    pass


class QualarooTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel68 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem114(TriggerRelationshipItem):
    pass


class SALESmanagoTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel69 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem115(TriggerRelationshipItem):
    pass


class SalesforcePardotTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel70 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem116(TriggerRelationshipItem):
    pass


class VideoHTML5Tag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel71 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem117(TriggerRelationshipItem):
    pass


class VideoYouTubeTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel72 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem118(TriggerRelationshipItem):
    pass


class HeatmapsTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel73 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem119(TriggerRelationshipItem):
    pass


class AbandonedTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel74 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem120(TriggerRelationshipItem):
    pass


class EcommerceOrder2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel75 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem121(TriggerRelationshipItem):
    pass


class EcommerceAddToCart2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel76 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem122(TriggerRelationshipItem):
    pass


class EcommerceRemoveFromCart2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel77 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem123(TriggerRelationshipItem):
    pass


class EcommerceProductDetailView2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel78 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem124(TriggerRelationshipItem):
    pass


class EcommerceCartUpdate2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel79 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem125(TriggerRelationshipItem):
    pass


class CookieInformationCMPIntegrationTag2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel80 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem126(TriggerRelationshipItem):
    pass


class CustomTagSynchronousDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel81 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem127(TriggerRelationshipItem):
    pass


class ABTastyTagDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel82 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem128(TriggerRelationshipItem):
    pass


class ClicktaleTagDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel83 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem129(TriggerRelationshipItem):
    pass


class DoubleClickConversionTagDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel84 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem130(TriggerRelationshipItem):
    pass


class OptimizelyTagDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel85 = Field(..., title="JSON:API 1.0 response data")


class TriggerRelationshipItem131(TriggerRelationshipItem):
    pass


class VisualWebsiteOptimizerTagDEPRECATED2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel86 = Field(..., title="JSON:API 1.0 response data")


class ApiTagV1AppIdTagsTagIdGetResponse(
    RootModel[
        Union[
            CustomTagAsynchronous2,
            CustomContent2,
            CustomPopup2,
            PiwikPROTag2,
            PiwikPROCustomDimensionsTag2,
            PiwikPROCustomEventTag2,
            PiwikPROGoalConversionTag2,
            PiwikPROVirtualPageViewTag2,
            AdrollTag2,
            BingAdsTag2,
            CrazyEggTag2,
            FloodlightSalesItemSoldTag2,
            FloodlightSalesTransactionsTag2,
            FloodlightCounterSessionTag2,
            FloodlightCounterStandardMethodTag2,
            FloodlightCounterUniqueMethodTag2,
            MetaPixelTag2,
            GoogleAdsRemarketingTag2,
            GoogleAdsTrackingConversionTag2,
            GoogleAnalyticsTag2,
            HotjarTag2,
            HubSpotTag2,
            LinkedInTag2,
            MarketoTag2,
            MauticTag2,
            QualarooTag2,
            SALESmanagoTag2,
            SalesforcePardotTag2,
            VideoHTML5Tag2,
            VideoYouTubeTag2,
            HeatmapsTag2,
            AbandonedTag2,
            EcommerceOrder2,
            EcommerceAddToCart2,
            EcommerceRemoveFromCart2,
            EcommerceProductDetailView2,
            EcommerceCartUpdate2,
            CookieInformationCMPIntegrationTag2,
            CustomTagSynchronousDEPRECATED2,
            ABTastyTagDEPRECATED2,
            ClicktaleTagDEPRECATED2,
            DoubleClickConversionTagDEPRECATED2,
            OptimizelyTagDEPRECATED2,
            VisualWebsiteOptimizerTagDEPRECATED2,
        ]
    ]
):
    root: Union[
        CustomTagAsynchronous2,
        CustomContent2,
        CustomPopup2,
        PiwikPROTag2,
        PiwikPROCustomDimensionsTag2,
        PiwikPROCustomEventTag2,
        PiwikPROGoalConversionTag2,
        PiwikPROVirtualPageViewTag2,
        AdrollTag2,
        BingAdsTag2,
        CrazyEggTag2,
        FloodlightSalesItemSoldTag2,
        FloodlightSalesTransactionsTag2,
        FloodlightCounterSessionTag2,
        FloodlightCounterStandardMethodTag2,
        FloodlightCounterUniqueMethodTag2,
        MetaPixelTag2,
        GoogleAdsRemarketingTag2,
        GoogleAdsTrackingConversionTag2,
        GoogleAnalyticsTag2,
        HotjarTag2,
        HubSpotTag2,
        LinkedInTag2,
        MarketoTag2,
        MauticTag2,
        QualarooTag2,
        SALESmanagoTag2,
        SalesforcePardotTag2,
        VideoHTML5Tag2,
        VideoYouTubeTag2,
        HeatmapsTag2,
        AbandonedTag2,
        EcommerceOrder2,
        EcommerceAddToCart2,
        EcommerceRemoveFromCart2,
        EcommerceProductDetailView2,
        EcommerceCartUpdate2,
        CookieInformationCMPIntegrationTag2,
        CustomTagSynchronousDEPRECATED2,
        ABTastyTagDEPRECATED2,
        ClicktaleTagDEPRECATED2,
        DoubleClickConversionTagDEPRECATED2,
        OptimizelyTagDEPRECATED2,
        VisualWebsiteOptimizerTagDEPRECATED2,
    ] = Field(..., description="Tag details response")


class Error18(Error14):
    pass


class ApiTagV1AppIdTagsTagIdGetResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error18] = Field(..., min_length=1)


class Error19(Error14):
    pass


class ApiTagV1AppIdTagsTagIdGetResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error19] = Field(..., min_length=1)


class Error20(Error14):
    pass


class ApiTagV1AppIdTagsTagIdGetResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error20] = Field(..., min_length=1)


class Error21(Error14):
    pass


class ApiTagV1AppIdTagsTagIdGetResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error21] = Field(..., min_length=1)


class TriggerRelationshipItem132(TriggerRelationshipItem):
    pass


class CustomTagAsynchronous3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel43 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem133(TriggerRelationshipItem):
    pass


class CustomContent3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel44 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem134(TriggerRelationshipItem):
    pass


class CustomPopup3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel45 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem135(TriggerRelationshipItem):
    pass


class PiwikPROTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel46 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem136(TriggerRelationshipItem):
    pass


class PiwikPROCustomDimensionsTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel47 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem137(TriggerRelationshipItem):
    pass


class PiwikPROCustomEventTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel48 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem138(TriggerRelationshipItem):
    pass


class PiwikPROGoalConversionTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel49 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem139(TriggerRelationshipItem):
    pass


class PiwikPROVirtualPageViewTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel50 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem140(TriggerRelationshipItem):
    pass


class AdrollTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel51 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem141(TriggerRelationshipItem):
    pass


class BingAdsTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel52 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem142(TriggerRelationshipItem):
    pass


class CrazyEggTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel53 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem143(TriggerRelationshipItem):
    pass


class FloodlightSalesItemSoldTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel54 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem144(TriggerRelationshipItem):
    pass


class FloodlightSalesTransactionsTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel55 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem145(TriggerRelationshipItem):
    pass


class FloodlightCounterSessionTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel56 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem146(TriggerRelationshipItem):
    pass


class FloodlightCounterStandardMethodTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel57 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem147(TriggerRelationshipItem):
    pass


class FloodlightCounterUniqueMethodTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel58 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem148(TriggerRelationshipItem):
    pass


class MetaPixelTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel59 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem149(TriggerRelationshipItem):
    pass


class GoogleAdsRemarketingTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel60 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem150(TriggerRelationshipItem):
    pass


class GoogleAdsTrackingConversionTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel61 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem151(TriggerRelationshipItem):
    pass


class GoogleAnalyticsTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel62 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem152(TriggerRelationshipItem):
    pass


class HotjarTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel63 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem153(TriggerRelationshipItem):
    pass


class HubSpotTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel64 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem154(TriggerRelationshipItem):
    pass


class LinkedInTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel65 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem155(TriggerRelationshipItem):
    pass


class MarketoTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel66 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem156(TriggerRelationshipItem):
    pass


class MauticTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel67 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem157(TriggerRelationshipItem):
    pass


class QualarooTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel68 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem158(TriggerRelationshipItem):
    pass


class SALESmanagoTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel69 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem159(TriggerRelationshipItem):
    pass


class SalesforcePardotTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel70 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem160(TriggerRelationshipItem):
    pass


class VideoHTML5Tag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel71 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem161(TriggerRelationshipItem):
    pass


class VideoYouTubeTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel72 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem162(TriggerRelationshipItem):
    pass


class HeatmapsTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel73 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem163(TriggerRelationshipItem):
    pass


class AbandonedTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel74 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem164(TriggerRelationshipItem):
    pass


class EcommerceOrder3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel75 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem165(TriggerRelationshipItem):
    pass


class EcommerceAddToCart3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel76 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem166(TriggerRelationshipItem):
    pass


class EcommerceRemoveFromCart3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel77 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem167(TriggerRelationshipItem):
    pass


class EcommerceProductDetailView3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel78 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem168(TriggerRelationshipItem):
    pass


class EcommerceCartUpdate3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel79 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem169(TriggerRelationshipItem):
    pass


class CookieInformationCMPIntegrationTag3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel80 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem170(TriggerRelationshipItem):
    pass


class CustomTagSynchronousDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel81 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem171(TriggerRelationshipItem):
    pass


class ABTastyTagDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel82 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem172(TriggerRelationshipItem):
    pass


class ClicktaleTagDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel83 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem173(TriggerRelationshipItem):
    pass


class DoubleClickConversionTagDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel84 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem174(TriggerRelationshipItem):
    pass


class OptimizelyTagDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel85 = Field(..., title="JSON:API 1.0 request data")


class TriggerRelationshipItem175(TriggerRelationshipItem):
    pass


class VisualWebsiteOptimizerTagDEPRECATED3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel86 = Field(..., title="JSON:API 1.0 request data")


class ApiTagV1AppIdTagsTagIdPatchRequest(
    RootModel[
        Union[
            CustomTagAsynchronous3,
            CustomContent3,
            CustomPopup3,
            PiwikPROTag3,
            PiwikPROCustomDimensionsTag3,
            PiwikPROCustomEventTag3,
            PiwikPROGoalConversionTag3,
            PiwikPROVirtualPageViewTag3,
            AdrollTag3,
            BingAdsTag3,
            CrazyEggTag3,
            FloodlightSalesItemSoldTag3,
            FloodlightSalesTransactionsTag3,
            FloodlightCounterSessionTag3,
            FloodlightCounterStandardMethodTag3,
            FloodlightCounterUniqueMethodTag3,
            MetaPixelTag3,
            GoogleAdsRemarketingTag3,
            GoogleAdsTrackingConversionTag3,
            GoogleAnalyticsTag3,
            HotjarTag3,
            HubSpotTag3,
            LinkedInTag3,
            MarketoTag3,
            MauticTag3,
            QualarooTag3,
            SALESmanagoTag3,
            SalesforcePardotTag3,
            VideoHTML5Tag3,
            VideoYouTubeTag3,
            HeatmapsTag3,
            AbandonedTag3,
            EcommerceOrder3,
            EcommerceAddToCart3,
            EcommerceRemoveFromCart3,
            EcommerceProductDetailView3,
            EcommerceCartUpdate3,
            CookieInformationCMPIntegrationTag3,
            CustomTagSynchronousDEPRECATED3,
            ABTastyTagDEPRECATED3,
            ClicktaleTagDEPRECATED3,
            DoubleClickConversionTagDEPRECATED3,
            OptimizelyTagDEPRECATED3,
            VisualWebsiteOptimizerTagDEPRECATED3,
        ]
    ]
):
    root: Union[
        CustomTagAsynchronous3,
        CustomContent3,
        CustomPopup3,
        PiwikPROTag3,
        PiwikPROCustomDimensionsTag3,
        PiwikPROCustomEventTag3,
        PiwikPROGoalConversionTag3,
        PiwikPROVirtualPageViewTag3,
        AdrollTag3,
        BingAdsTag3,
        CrazyEggTag3,
        FloodlightSalesItemSoldTag3,
        FloodlightSalesTransactionsTag3,
        FloodlightCounterSessionTag3,
        FloodlightCounterStandardMethodTag3,
        FloodlightCounterUniqueMethodTag3,
        MetaPixelTag3,
        GoogleAdsRemarketingTag3,
        GoogleAdsTrackingConversionTag3,
        GoogleAnalyticsTag3,
        HotjarTag3,
        HubSpotTag3,
        LinkedInTag3,
        MarketoTag3,
        MauticTag3,
        QualarooTag3,
        SALESmanagoTag3,
        SalesforcePardotTag3,
        VideoHTML5Tag3,
        VideoYouTubeTag3,
        HeatmapsTag3,
        AbandonedTag3,
        EcommerceOrder3,
        EcommerceAddToCart3,
        EcommerceRemoveFromCart3,
        EcommerceProductDetailView3,
        EcommerceCartUpdate3,
        CookieInformationCMPIntegrationTag3,
        CustomTagSynchronousDEPRECATED3,
        ABTastyTagDEPRECATED3,
        ClicktaleTagDEPRECATED3,
        DoubleClickConversionTagDEPRECATED3,
        OptimizelyTagDEPRECATED3,
        VisualWebsiteOptimizerTagDEPRECATED3,
    ] = Field(..., description="Tag edit request")


class Error22(Error14):
    pass


class ApiTagV1AppIdTagsTagIdPatchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error22] = Field(..., min_length=1)


class Error23(Error14):
    pass


class ApiTagV1AppIdTagsTagIdPatchResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error23] = Field(..., min_length=1)


class Error24(Error14):
    pass


class ApiTagV1AppIdTagsTagIdPatchResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error24] = Field(..., min_length=1)


class Error25(Error14):
    pass


class ApiTagV1AppIdTagsTagIdPatchResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error25] = Field(..., min_length=1)


class Error26(Error14):
    pass


class ApiTagV1AppIdTagsTagIdPatchResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error26] = Field(..., min_length=1)


class Error27(Error14):
    pass


class ApiTagV1AppIdTagsTagIdDeleteResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error27] = Field(..., min_length=1)


class Error28(Error14):
    pass


class ApiTagV1AppIdTagsTagIdDeleteResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error28] = Field(..., min_length=1)


class Error29(Error14):
    pass


class ApiTagV1AppIdTagsTagIdDeleteResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error29] = Field(..., min_length=1)


class Error30(Error14):
    pass


class ApiTagV1AppIdTagsTagIdDeleteResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error30] = Field(..., min_length=1)


class Error31(Error14):
    pass


class ApiTagV1AppIdTagsTagIdDeleteResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error31] = Field(..., min_length=1)


class ApiTagV1AppIdTagsTagIdCopyPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0RequestDataModel87 = Field(..., title="JSON:API 1.0 request data")


class ApiTagV1AppIdTagsTagIdCopyPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: JSON_API_1.Field0ResponseDataModel87 = Field(..., title="JSON:API 1.0 response data")


class Error32(Error14):
    pass


class ApiTagV1AppIdTagsTagIdCopyPostResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error32] = Field(..., min_length=1)


class Error33(Error14):
    pass


class ApiTagV1AppIdTagsTagIdCopyPostResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error33] = Field(..., min_length=1)


class Error34(Error14):
    pass


class ApiTagV1AppIdTagsTagIdCopyPostResponse3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error34] = Field(..., min_length=1)


class Error35(Error14):
    pass


class ApiTagV1AppIdTagsTagIdCopyPostResponse4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error35] = Field(..., min_length=1)


class Error36(Error14):
    pass


class ApiTagV1AppIdTagsTagIdCopyPostResponse5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: List[Error36] = Field(..., min_length=1)
